[webservers]
portfolio-node-1 ansible_host=44.202.118.41
portfolio-node-2 ansible_host=54.221.57.33


[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/Jeni.pem
ansible_python_interpreter=/usr/bin/python3